<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageVersion Include="SimpleInjector" Version="5.6.0" />
    <PackageVersion Include="TUnit" Version="1.68.17" />
  </ItemGroup>
</Project>